### ISSUE TITLE
Ultra buggy. Do not use in current state.

### ISSUE THREAD

**Issue by JFosterRP** [TanguyOrtegat/esx_jb_eden_garage2#36] opened 2019-07-20 00:49 UTC
3 Sep. Markers (ugly)
Terribly Optimized
You can still dupe vehicles
If you explode your vehicle nearby good luck getting it back
Too much esx_help integration (ugly)

**Comment by XvenDeR** [comment] 2019-07-30 20:43
To get vehicle after exploding you gotta put these

```
exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanodeletepoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanospawnpoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")
```

Somewhere... that I have no idea where to be honest.

**Comment by TanguyOrtegat** [comment] 2019-08-03 12:56
there is no dupe of vehicles

**Closed** 2019-08-16 09:31 UTC
