### ISSUE TITLE
duplicate car with impound

### ISSUE THREAD

**Issue by Heady20006** [TanguyOrtegat/esx_jb_eden_garage2#9] opened 2019-01-16 01:07 UTC
i can spawn infinite police cars if i buy one and store it in the publicgarage. then i can use the impound to spawn one after another.
is there anyfix which i can´t found?

**Comment by TanguyOrtegat** [comment] 2019-01-17 17:01
any errors ? f8/ server console?

**Comment by Heady20006** [comment] 2019-01-20 16:47
nope. no errors. need this script mysql-async 3.x or 2.x?

**Comment by Heady20006** [comment] 2019-01-22 19:21
no idea? How is the script checking if the car is out off the garage? with state 0? then normaly everyone should have this issue isnt it?

**Comment by TanguyOrtegat** [comment] 2019-01-23 20:58
thx for video i ll look into it :) because normally the vehicle you get out, is saved clientsided to check if the car still exists

**Comment by TanguyOrtegat** [comment] 2019-01-23 21:00
duplication has nothing to do with sql, just he doesn't know or check the entity if it still exists

**Comment by Heady20006** [comment] 2019-01-26 16:45
Ah okay. and where is the function for saving clientside? maybe there is another script which is not in love with your garage ^^

**Comment by TanguyOrtegat** [comment] 2019-01-28 12:19
you restart ft_libs after that ?

**Comment by zabattaro** [comment] 2019-01-28 15:17
Im having the same glitch, if ur car is out u can go to the impound and call your car what ever times you want http://prntscr.com/mdb34w

**Comment by TanguyOrtegat** [comment] 2019-01-28 17:31
becasue here you can see this: 
https://github.com/TanguyOrtegat/esx_jb_eden_garage2/blob/master/esx_jb_eden_garage2_cl.lua#L284
that line serves to put in a table the vehicle you get out

and here you get the line to check weather the vehicle is out or not
https://github.com/TanguyOrtegat/esx_jb_eden_garage2/blob/master/esx_jb_eden_garage2_cl.lua#L358

**Comment by zabattaro** [comment] 2019-01-29 19:35
It just dont detect which are on garage or out or whatever. It let you get the car from de impound always

**Comment by Heady20006** [comment] 2019-01-29 21:39
i can get the car out of the garage and then just one time from the impound.

**Comment by TanguyOrtegat** [comment] 2019-02-03 15:06
i should go to yor server and see

**Comment by desperadisse** [comment] 2019-02-14 01:37
same error, have you got an answer ?

**Comment by TanguyOrtegat** [comment] 2019-03-18 16:20
i should go to you server and check and debug, because duping on my server doesn't work , but in a server i went it was possible. so i need to check into you server and debug in your files

**Comment by rafakid** [comment] 2019-03-30 03:08
the same thing happens to me, the cars are duplicated

**Comment by DonKKijotE** [comment] 2019-04-18 14:43
Hi, I just started in this RP and ESX thing and don't know much about LUA. However, I Can code in other languages and by looking at the code I'm guessing the "error" might be in esx_jb_eden_garage2_cl.lua, on line 358 you have this:

	if not iscaronearth then
					ESX.TriggerServerCallback('eden_garage:checkMoney', function(hasEnoughMoney)
						if hasEnoughMoney then
							menu.close()
							SpawnVehicle(data.current.value, garage, KindOfVehicle)

Shouldn't you delete the already existing car before spawning the vehicle?

Thanks on beforehand and hope the info is useful!

**Comment by TanguyOrtegat** [comment] 2019-04-18 20:30
we could do that way that we delete the car before spawning a car, the thing is that this could be misused (to repair car or other things like that) i do check if car is on earth by the native doesentityexists if it returns true then the carisonearth otherwise not. 
it does work on my server, but i still have no clue why it wouldn(t work on any other server ... 
thanks for giving input and hopfully fix that issue

**Comment by DonKKijotE** [comment] 2019-04-18 20:52
Hey Tanguy, I think I will try 2 options: first as a quick fix disable the inpound and second maybe try to get it working on my server. I am a bit confused but I will have to read some LUA tutorial to get the hang of it...

The thing is I noticed that if I close the server the cars that weren't in the garage go missing, so if there's no inpound they cannot get their cars back. I will try to see how to work around this :)

Good work man ! 👍

**Comment by DonKKijotE** [comment] 2019-04-19 20:10
Hi guys, in case anyone wants to use the script you can disable the possibility of respawning the vehicle in the yellow blip just by commenting a line. I think we should see why some of us are getting this mistake... Meanwhile by doing the following you disable your vehicles menu in the recover option so you cannot get any of yours cars back, you have to either get it fixed by a mechanic or talk to an admin. 

You have to go to esx_jb_eden_garage2_cl.lua, line 52 and change

	ReturnVehicleMenu(garage, KindOfVehicle)

into

	--ReturnVehicleMenu(garage, KindOfVehicle)

This way you won't see the vehicles menu and therefore it won't be possible to respawn one. Obviously it's not a perfect fix, but if you're in a hurry like me you can go ahead and use Tanguys resource with this fix :)

**Comment by TanguyOrtegat** [comment] 2019-04-21 11:00
@DonKKijotE  maybe you can print out car enitys and you car car wouldn't be on earth because it is still there... So we could fix that issue, is teh entity number saved as local numbernot the same as the one we check or any other issue ? 

If you could print out some variables lins iscaroneath vehicleentity... to check where is goes wrong. thank you

**Comment by DonKKijotE** [comment] 2019-04-22 14:14
Hey Tanguy, sorry I hadn't replied. I will try to debug it today or tomorrow and see if we can fix it. I would like to ask you, since I'm not too experienced on fivem or lua, do you know if it's possible to run a onResourceStart handler for eden_garage2? If so with that event you could make a fix to return all car states to stored=1 when the server restarts/crashes and eden_garage2 is loaded... I will try this and the debug process myself soon hopefully :) Have a nice day!

**Comment by TanguyOrtegat** [comment] 2019-04-22 20:59
@DonKKijotE  just create a thread on server side and with what you want in it :) and when you restart the script it will execute it on the start of the script

**Comment by brugillo** [comment] 2019-04-30 08:18
I found the problem and I fix it but OMG what a stupid thing.

Sorry if I'm not reporting it correctly as it is my first time posting in GitHub.

In the client file, on the line 349
		if v.plate == (data.current.value.plate) then
the problem is the v,plate is returning an extra space on the plate (not sure why or from where) as I just started with all this scripting thing like 1 week back, not sure if this is a default feature from FiveM or it is another kind of bug.

anyways how I solved was adding a space at the end of the current plate:
					if v.plate == (data.current.value.plate.." ") then

If you have any different way to solve this, please let me know

**Comment by TanguyOrtegat** [comment] 2019-04-30 14:47
@brugillo use the esx trim function to get your plate :)

**Comment by TanguyOrtegat** [comment] 2019-05-31 14:54
fixed  now, can you try new version and tell me :)

**Closed** 2019-06-02 22:12 UTC
